# Generated by Django 5.2 on 2025-10-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'INIT'), ('in_progress', 'IN_PROGRESS'), ('finished', 'FINISHED')], default='init', max_length=12),
            preserve_default=False,
        ),
    ]
