# Generated by Django 5.2 on 2025-10-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'INIT'), ('in_progress', 'IN_PROGRESS'), ('finished', 'FINISHED')], default='init', max_length=12),
        ),
    ]
