# Generated by Django 5.2 on 2025-10-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_alter_athleteinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
