# Generated by Django 5.2 on 2025-11-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_collectibleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
