# Generated by Django 5.2 on 2025-11-06 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_collectibleitem_itmes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectibleitem',
            name='itmes',
        ),
        migrations.AddField(
            model_name='collectibleitem',
            name='athletes',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
