# Generated by Django 5.2 on 2025-11-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0012_remove_collectibleitem_itmes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(default='2020-01-01T12:00:00.000'),
        ),
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
