# Generated by Django 5.2 on 2025-11-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_position_date_time_run_run_time_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(default='0000-01-01T00:00:00.000'),
        ),
    ]
