# Generated by Django 5.2 on 2025-11-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0015_alter_collectibleitem_athletes'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
