# Generated by Django 5.2 on 2025-11-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0018_coachraiting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coachraiting',
            unique_together=set(),
        ),
    ]
