# Generated by Django 5.2 on 2025-11-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0020_coachrating_delete_coachraiting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachrating',
            options={'verbose_name': 'Рейтинг тренера', 'verbose_name_plural': 'Рейтинги тренера'},
        ),
    ]
