# Generated by Django 5.2 on 2025-11-17 15:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0021_alter_coachrating_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athleteinfo',
            options={'verbose_name': 'Атлет', 'verbose_name_plural': 'Атлеты'},
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'verbose_name': 'Челлендж', 'verbose_name_plural': 'Челленджи'},
        ),
        migrations.AlterModelOptions(
            name='coachrating',
            options={'verbose_name': 'Оценка тренера', 'verbose_name_plural': 'Оценки тренера'},
        ),
        migrations.AlterModelOptions(
            name='collectibleitem',
            options={'verbose_name': 'Коллекционный предмет', 'verbose_name_plural': 'Коллекционные предметы'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'verbose_name': 'Забег', 'verbose_name_plural': 'Забеги'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписка на тренера', 'verbose_name_plural': 'Подписки на тренера'},
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цели'),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete', to=settings.AUTH_USER_MODEL, verbose_name='Атлет'),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL, verbose_name='Атлет'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='coachrating',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_by_athlete', to=settings.AUTH_USER_MODEL, verbose_name='Атлет'),
        ),
        migrations.AlterField(
            model_name='coachrating',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_to_coach', to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='coachrating',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='athletes',
            field=models.ManyToManyField(blank=True, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Атлет'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='picture',
            field=models.URLField(verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='uid',
            field=models.CharField(max_length=10, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='value',
            field=models.PositiveSmallIntegerField(verbose_name='Значение/бонус'),
        ),
        migrations.AlterField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(default='0000-01-01T00:00:00.000', verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='position',
            name='distance',
            field=models.FloatField(default=0, verbose_name='Расстояние'),
        ),
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='position',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app_run.run', verbose_name='Забег'),
        ),
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0, verbose_name='Скорость'),
        ),
        migrations.AlterField(
            model_name='run',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL, verbose_name='Атлет'),
        ),
        migrations.AlterField(
            model_name='run',
            name='comment',
            field=models.CharField(max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='run',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время забега'),
        ),
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Расстояние'),
        ),
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Время забега'),
        ),
        migrations.AlterField(
            model_name='run',
            name='speed',
            field=models.FloatField(default=0, verbose_name='Средняя скорость забега'),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'INIT'), ('in_progress', 'IN_PROGRESS'), ('finished', 'FINISHED')], default='init', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Атлет'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
    ]
